// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1NZQqdy_yvttLTFWM-A1G6CgyCwPfzZ4',
    appId: '1:510154005717:android:9e94807ce89fe5fb0c165c',
    messagingSenderId: '510154005717',
    projectId: 'simple-calculator-99d7f',
    storageBucket: 'simple-calculator-99d7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPS8fXPQC9c1lNi8cqKkHgL3Q_AttQHEI',
    appId: '1:510154005717:ios:a2cbbb0b1f6a01420c165c',
    messagingSenderId: '510154005717',
    projectId: 'simple-calculator-99d7f',
    storageBucket: 'simple-calculator-99d7f.firebasestorage.app',
    iosBundleId: 'com.stairlabs.simpleCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABfeIgkmNUAKTnaZWuQa8EMETPbACAmzU',
    appId: '1:510154005717:web:d191dabe82cdaf1a0c165c',
    messagingSenderId: '510154005717',
    projectId: 'simple-calculator-99d7f',
    authDomain: 'simple-calculator-99d7f.firebaseapp.com',
    storageBucket: 'simple-calculator-99d7f.firebasestorage.app',
  );
}
